spring.application.name=api

# * === Banco de Dados ===

spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${URL_DATABASE}/${DATABASE_NAME}?stringtype=unspecified

# * === JPA / Hibernate ===

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# * === Importações ===

spring.config.import=classpath:custom.properties

# * === Quartz ===

spring.quartz.job-store-type=memory
spring.quartz.overwrite-existing-jobs=true
