# * === URLs ===

url.frontend=https://front-clin-play.vercel.app

# * === Contratos ===

contract.privacy-policy.version=1.0
contract.terms-of-service.version=1.0

# * === Documentação ===

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# * === JWT ===

jwt.setup.expiration=1800000
jwt.access.expiration=1800000
jwt.refresh.expiration=31536000000

# * === Scheduler ===

database.delete-log.after=94608000000
database.delete-inactive-session.after=315360000

# * === OAuth2 ===

oauth2.google.client-id=${OAUTH_GOOGLE_CLIENT_ID}
oauth2.google.client-secret=${OAUTH_GOOGLE_CLIENT_SECRET}

# * === Secret ===

security.secret=${SECURITY_SECRET}

# * === Firebase ===

firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH}
